spring.application.name=Vita-Flow

server.baseUrl=${BASE_URL}
server.port=${PORT}

spring.config.import=optional:file:.env[.properties]

#data source url
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}


# jpa configuration
spring.jpa.show-sql=${SHOW_SQL}

# for creating and updating tables automatically
spring.jpa.hibernate.ddl-auto=${DDL_AUTO}

# spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Email Configuration
spring.mail.host=${EMAIL_HOST}
spring.mail.port=${EMAIL_PORT}
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
